In [6]:
import pandas as pd

In [34]:
df = pd.DataFrame({
    "locatie": ["locatie1", "locatie1", "locatie1", "locatie2", "locatie2", "locatie2", "locatie3", "locatie3"],
    "category": ["A", "B", "C", "A", "B", "C", "B", "C"],
    "value": [10, 20, 30, 40, 50, 60, 70, 80]
})

In [35]:
df

    locatie category  value
0  locatie1        A     10
1  locatie1        B     20
2  locatie1        C     30
3  locatie2        A     40
4  locatie2        B     50
5  locatie2        C     60
6  locatie3        B     70
7  locatie3        C     80

In [36]:
df_out = df.pivot(index="locatie", columns="category", values="value").reset_index()
df_out.columns.name = None
df_out

    locatie     A     B     C
0  locatie1  10.0  20.0  30.0
1  locatie2  40.0  50.0  60.0
2  locatie3   NaN  70.0  80.0

In [33]:
df.duplicated(subset=["locatie", "category"]).any()

False

In [74]:
df = pd.DataFrame({
    "locatie": ["loc1"]*12 + ["loc2"]*12 + ["loc3"]*12,
    "start": ["2024-01-01"]*6 + ["2025-01-01"]*6 + ["2024-01-01"]*6 + ["2025-01-01"]*6 + ["2024-01-01"]*6 + ["2025-01-01"]*6,
    "eind": ["2024-12-31"]*6 + ["2025-12-31"]*6 + ["2024-12-31"]*6 + ["2025-12-31"]*6 + ["2024-12-31"]*6 + ["2025-12-31"]*6,
    "category": ["A", "B", "C", "D", "E", "F"]*6,
    "value": [10, 20, 30, 40, 50, 60, 15, 25, 35, 45, 55, 65]*3
})

In [75]:
df

   locatie       start        eind category  value
0     loc1  2024-01-01  2024-12-31        A     10
1     loc1  2024-01-01  2024-12-31        B     20
2     loc1  2024-01-01  2024-12-31        C     30
3     loc1  2024-01-01  2024-12-31        D     40
4     loc1  2024-01-01  2024-12-31        E     50
5     loc1  2024-01-01  2024-12-31        F     60
6     loc1  2025-01-01  2025-12-31        A     15
7     loc1  2025-01-01  2025-12-31        B     25
8     loc1  2025-01-01  2025-12-31        C     35
9     loc1  2025-01-01  2025-12-31        D     45
10    loc1  2025-01-01  2025-12-31        E     55
11    loc1  2025-01-01  2025-12-31        F     65
12    loc2  2024-01-01  2024-12-31        A     10
13    loc2  2024-01-01  2024-12-31        B     20
14    loc2  2024-01-01  2024-12-31        C     30
15    loc2  2024-01-01  2024-12-31        D     40
16    loc2  2024-01-01  2024-12-31        E     50
17    loc2  2024-01-01  2024-12-31        F     60
18    loc2  2025-01-01  2025-12-31        A     15
19    loc2  2025-01-01  2025-12-31        B     25
20    loc2  2025-01-01  2025-12-31        C     35
21    loc2  2025-01-01  2025-12-31        D     45
22    loc2  2025-01-01  2025-12-31        E     55
23    loc2  2025-01-01  2025-12-31        F     65
24    loc3  2024-01-01  2024-12-31        A     10
25    loc3  2024-01-01  2024-12-31        B     20
26    loc3  2024-01-01  2024-12-31        C     30
27    loc3  2024-01-01  2024-12-31        D     40
28    loc3  2024-01-01  2024-12-31        E     50
29    loc3  2024-01-01  2024-12-31        F     60
30    loc3  2025-01-01  2025-12-31        A     15
31    loc3  2025-01-01  2025-12-31        B     25
32    loc3  2025-01-01  2025-12-31        C     35
33    loc3  2025-01-01  2025-12-31        D     45
34    loc3  2025-01-01  2025-12-31        E     55
35    loc3  2025-01-01  2025-12-31        F     65

In [76]:
df_out = df.pivot(
    index=["locatie", "start", "eind"], 
    columns="category", 
    values="value"
).reset_index()

df_out.columns.name = None

normaal gezien hoeft start en eind niet want eind zal altijd = null

In [77]:
df_out

  locatie       start        eind   A   B   C   D   E   F
0    loc1  2024-01-01  2024-12-31  10  20  30  40  50  60
1    loc1  2025-01-01  2025-12-31  15  25  35  45  55  65
2    loc2  2024-01-01  2024-12-31  10  20  30  40  50  60
3    loc2  2025-01-01  2025-12-31  15  25  35  45  55  65
4    loc3  2024-01-01  2024-12-31  10  20  30  40  50  60
5    loc3  2025-01-01  2025-12-31  15  25  35  45  55  65

In [81]:
df2 = pd.DataFrame({
    "locatie": ["loc1", "loc1"],
    "eigenschap": ["x", "y"]
})

In [82]:
df2

  locatie eigenschap
0    loc1          x
1    loc1          y

In [83]:
df_joined = pd.merge(df_out, df2, on="locatie", how="left")
df_joined

  locatie       start        eind   A   B   C   D   E   F eigenschap
0    loc1  2024-01-01  2024-12-31  10  20  30  40  50  60          x
1    loc1  2024-01-01  2024-12-31  10  20  30  40  50  60          y
2    loc1  2025-01-01  2025-12-31  15  25  35  45  55  65          x
3    loc1  2025-01-01  2025-12-31  15  25  35  45  55  65          y
4    loc2  2024-01-01  2024-12-31  10  20  30  40  50  60        NaN
5    loc2  2025-01-01  2025-12-31  15  25  35  45  55  65        NaN
6    loc3  2024-01-01  2024-12-31  10  20  30  40  50  60        NaN
7    loc3  2025-01-01  2025-12-31  15  25  35  45  55  65        NaN

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({
    'kolomA': [1, 2, 3],
    'kolomB': ['x', 'y', 'z'],
    'waarde1': [10, 20, 30]
})

df2 = pd.DataFrame({
    'kolomA': [1, 2, 3],
    'kolomB': ['x', 'y', 'z'],
    'waarde2': [100, 200, 300]
})

In [ ]:
df1

In [ ]:
df2